name: Github to Drupal code

on: [push, delete]

jobs:
  to_drupalcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@git.drupal.org:project/gitlab_integration.git
          ssh_private_key:
            ${{ secrets.DRUPAL_SSH_PRIVATE_KEY }}
